version: '3.1'

services:
  piraremission-back:
    build:
      context: ./BACK
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    container_name: piraremission_back
    restart: always
    ports:
      - 3322:8080
    environment:
      - TZ=America/Bogota
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
  piraremission-front:
    build:
      context: ./FRONT
    container_name: piraremission_front
    restart: always
    ports:
      - 3321:80
